name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '22.16.0'

    - name: Install dependencies
      run: |
        yarn install

    - name: Create dotenv file
      working-directory: ./packages/metastream-app
      run: |
        echo "${{ secrets.DOTENV_CONTENTS }}" >> .env

    - name: Build signal server
      working-directory: ./packages/metastream-signal-server
      run: |
        yarn build

    - name: Build web app
      working-directory: ./packages/metastream-app
      run: |
        yarn build
      env:
        NODE_ENV: production

    - name: Deploy branch
      uses: s0/git-publish-subdir-action@v2.0.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./packages/metastream-app/dist
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
